default_apps = [
            {"status": "Not Applied", "name": "Akuna Capital", "open": "Chicago, IL", "close": "Jul 16", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Jane Street", "open": "New York, NY", "close": "Jul 16", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Wells Fargo", "open": "Multiple locations", "close": "Jul 17", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "TikTok", "open": "Los Angeles, CA", "close": "Jul 19", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "IXL Learning", "open": "San Mateo, CA", "close": "Jul 21", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "ATPCO", "open": "Remote in USA", "close": "Jul 23", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "ATPCO", "open": "Dulles, VA", "close": "Jul 23", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Sensata", "open": "Attleboro, MA", "close": "Jul 26", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Akuna Capital", "open": "Chicago, IL", "close": "Jul 29", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Amazon", "open": "Seattle, WA", "close": "Jul 29", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Virtu Financial", "open": "NYC", "close": "Jul 29", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "ByteDance", "open": "San Jose, CA", "close": "Jul 30", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Notion", "open": "New York, NY", "close": "Jul 30", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Notion", "open": "San Francisco, CA", "close": "Jul 30", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Motorola", "open": "Plantation, FL", "close": "Jul 31", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Motorola", "open": "Hoffman Estates, IL", "close": "Jul 31", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Codeium", "open": "Mountain View, CA", "close": "Aug 01", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "HPR (Hyannis Port Research)", "open": "Needham, MA", "close": "Aug 01", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Sentry", "open": "Toronto, ON, Canada", "close": "Aug 01", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Ventas", "open": "Chicago, IL", "close": "Aug 02", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Five Rings", "open": "New York", "close": "Aug 03", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Confluent", "open": "Remote", "close": "Aug 04", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Confluent", "open": "Austin, TX", "close": "Aug 04", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Databricks", "open": "Bellevue, WA", "close": "Aug 05", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Databricks", "open": "Mountain View, CA", "close": "Aug 05", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Databricks", "open": "SF", "close": "Aug 05", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Deloitte", "open": "New York, NY", "close": "Aug 05", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Deloitte", "open": "Austin, TX", "close": "Aug 05", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Deloitte", "open": "San Francisco, CA", "close": "Aug 05", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "TikTok", "open": "Vancouver, Canada", "close": "Aug 05", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Airwallex", "open": "SF", "close": "Aug 06", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Databricks", "open": "Bellevue, WA", "close": "Aug 06", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Databricks", "open": "Mountain View, CA", "close": "Aug 06", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Databricks", "open": "San Francisco, CA", "close": "Aug 06", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Strider Technologies", "open": "Vienna, VA", "close": "Aug 06", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Strider Technologies", "open": "South Jordan, UT", "close": "Aug 06", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Oshkosh", "open": "Oshkosh, WI", "close": "Aug 07", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Quantiq Partners", "open": "Austin, TX", "close": "Aug 07", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Belvedere Trading", "open": "Boulder, CO", "close": "Aug 09", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Belvedere Trading", "open": "Chicago, IL", "close": "Aug 09", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Jump Trading", "open": "Chicago, IL", "close": "Aug 09", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Neuralink", "open": "Austin, TX", "close": "Aug 09", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "DV Trading", "open": "Chicago, IL", "close": "Aug 12", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Qualcomm", "open": "San Diego, California", "close": "Aug 12", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Vestmark", "open": "Wakefield, MA", "close": "Aug 12", "link": "https://simplify.com/apply"},
            {"status": "Not Applied", "name": "Epic", "open": "Madison, WI", "close": "May 3, 2024", "link": "https://epic.avature.net/Careers/FolderDetail/Verona-Wisconsin-United-States-Software-Developer-Intern-Summer-2025/25624?utm_source=Simplify&ref=Simplify"},
            {"status": "Not Applied", "name": "Apple", "open": "United States", "close": "June 7, 2024", "link": "https://jobs.apple.com/en-us/details/200554359/software-engineering-internships?team=STDNT"}
        ]